// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	SigninRequest
	SigninResponse
	SignoutRequest
	SignoutResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/sgipc/web-api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SigninRequest struct {
	Roll        string `protobuf:"bytes,1,opt,name=roll" json:"roll,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Password    string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	CfUsername  string `protobuf:"bytes,5,opt,name=cf_username,json=cfUsername" json:"cf_username,omitempty"`
	UvaUsername string `protobuf:"bytes,6,opt,name=uva_username,json=uvaUsername" json:"uva_username,omitempty"`
	Status      string `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *SigninRequest) Reset()                    { *m = SigninRequest{} }
func (m *SigninRequest) String() string            { return proto.CompactTextString(m) }
func (*SigninRequest) ProtoMessage()               {}
func (*SigninRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SigninResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SigninResponse) Reset()                    { *m = SigninResponse{} }
func (m *SigninResponse) String() string            { return proto.CompactTextString(m) }
func (*SigninResponse) ProtoMessage()               {}
func (*SigninResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SigninResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SignoutRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *SignoutRequest) Reset()                    { *m = SignoutRequest{} }
func (m *SignoutRequest) String() string            { return proto.CompactTextString(m) }
func (*SignoutRequest) ProtoMessage()               {}
func (*SignoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SignoutResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SignoutResponse) Reset()                    { *m = SignoutResponse{} }
func (m *SignoutResponse) String() string            { return proto.CompactTextString(m) }
func (*SignoutResponse) ProtoMessage()               {}
func (*SignoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SignoutResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*SigninRequest)(nil), "auth.SigninRequest")
	proto.RegisterType((*SigninResponse)(nil), "auth.SigninResponse")
	proto.RegisterType((*SignoutRequest)(nil), "auth.SignoutRequest")
	proto.RegisterType((*SignoutResponse)(nil), "auth.SignoutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Authentication service

type AuthenticationClient interface {
	Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninResponse, error)
	Signout(ctx context.Context, in *SignoutRequest, opts ...grpc.CallOption) (*SignoutResponse, error)
}

type authenticationClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationClient(cc *grpc.ClientConn) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninResponse, error) {
	out := new(SigninResponse)
	err := grpc.Invoke(ctx, "/auth.Authentication/Signin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) Signout(ctx context.Context, in *SignoutRequest, opts ...grpc.CallOption) (*SignoutResponse, error) {
	out := new(SignoutResponse)
	err := grpc.Invoke(ctx, "/auth.Authentication/Signout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Authentication service

type AuthenticationServer interface {
	Signin(context.Context, *SigninRequest) (*SigninResponse, error)
	Signout(context.Context, *SignoutRequest) (*SignoutResponse, error)
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigninRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Signin(ctx, req.(*SigninRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_Signout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Signout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/Signout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Signout(ctx, req.(*SignoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signin",
			Handler:    _Authentication_Signin_Handler,
		},
		{
			MethodName: "Signout",
			Handler:    _Authentication_Signout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x95, 0x7e, 0xfd, 0x52, 0xb8, 0x85, 0x22, 0x19, 0x28, 0x51, 0x5a, 0x09, 0xea, 0x01,
	0x21, 0x24, 0x1a, 0xa9, 0x2c, 0xc0, 0xc6, 0xc6, 0xdc, 0x0a, 0x06, 0x16, 0xe4, 0xa6, 0x6e, 0x88,
	0x54, 0xec, 0x10, 0x3b, 0x54, 0xac, 0xbc, 0x02, 0xaf, 0xc4, 0xc6, 0xc8, 0x2b, 0xf0, 0x20, 0x38,
	0xd7, 0x49, 0xfa, 0x47, 0x2c, 0x4c, 0xf1, 0x3d, 0xf7, 0xe7, 0x13, 0x1f, 0x5f, 0x03, 0xb0, 0x4c,
	0x3f, 0xf6, 0x93, 0x54, 0x6a, 0x49, 0xea, 0xf9, 0xda, 0xef, 0x46, 0x52, 0x46, 0x33, 0x1e, 0xb0,
	0x24, 0x0e, 0x98, 0x10, 0x52, 0x33, 0x1d, 0x4b, 0xa1, 0x2c, 0xe3, 0x77, 0xe6, 0x7c, 0x7c, 0x96,
	0xb7, 0x26, 0xfa, 0x35, 0xe1, 0xaa, 0xf8, 0xd8, 0x26, 0xfd, 0x74, 0x60, 0x7b, 0x14, 0x47, 0x22,
	0x16, 0x43, 0xfe, 0x9c, 0x71, 0xa5, 0x09, 0x81, 0x7a, 0x2a, 0x67, 0x33, 0xcf, 0x39, 0x72, 0x4e,
	0x36, 0x87, 0xb8, 0x26, 0x3e, 0x6c, 0x64, 0x8a, 0xa7, 0x82, 0x3d, 0x71, 0xaf, 0x86, 0x7a, 0x55,
	0xe7, 0x3c, 0xea, 0xff, 0x2c, 0x8f, 0x9a, 0xe1, 0x13, 0xa6, 0xd4, 0x5c, 0xa6, 0x13, 0xaf, 0x6e,
	0xf9, 0xb2, 0x26, 0x87, 0xd0, 0x0c, 0xa7, 0x0f, 0x95, 0xdd, 0x7f, 0x6c, 0x43, 0x38, 0xbd, 0x2d,
	0x0d, 0x7b, 0xb0, 0x95, 0xbd, 0xb0, 0x05, 0xe1, 0x22, 0xd1, 0x34, 0x5a, 0x85, 0xb4, 0xc1, 0x55,
	0x26, 0x64, 0xa6, 0xbc, 0x06, 0x36, 0x8b, 0x8a, 0x5e, 0x40, 0xab, 0x0c, 0xa3, 0x12, 0x73, 0x03,
	0x9c, 0x1c, 0x57, 0x64, 0x9e, 0xa7, 0x39, 0x68, 0xf5, 0x8b, 0xf8, 0x23, 0x54, 0xab, 0x9d, 0x37,
	0x76, 0xa7, 0xcc, 0x74, 0x79, 0x0f, 0xcb, 0x99, 0x9d, 0xb5, 0xcc, 0xcb, 0xf9, 0x6a, 0xab, 0xf9,
	0xe8, 0x25, 0xec, 0x54, 0x4e, 0x7f, 0x3b, 0xc4, 0xe0, 0xc3, 0x81, 0xd6, 0xb5, 0x19, 0x28, 0x17,
	0x3a, 0x0e, 0x71, 0x86, 0xe4, 0x0e, 0x5c, 0x9b, 0x88, 0xec, 0xf6, 0x71, 0xee, 0x2b, 0xc3, 0xf2,
	0xf7, 0x56, 0x45, 0xfb, 0x3f, 0xda, 0x7b, 0xfb, 0xfa, 0x7e, 0xaf, 0x75, 0x68, 0x3b, 0x50, 0x51,
	0x9c, 0x84, 0xf6, 0x5d, 0x18, 0x2e, 0x50, 0xc8, 0x5d, 0x39, 0xa7, 0xe4, 0x1e, 0x1a, 0xc5, 0x29,
	0xc9, 0x92, 0xc7, 0x22, 0xbe, 0xbf, 0xbf, 0xa6, 0x16, 0xd6, 0x14, 0xad, 0xbb, 0xf4, 0xe0, 0x37,
	0x6b, 0x03, 0x1a, 0xef, 0xb1, 0x8b, 0x4f, 0xeb, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0x32, 0x16,
	0xb7, 0x9c, 0xa9, 0x02, 0x00, 0x00,
}
