// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	SignupRequest
	SigninRequest
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/sgipc/web-api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignupRequest struct {
	Roll        string `protobuf:"bytes,1,opt,name=roll" json:"roll,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Mail        string `protobuf:"bytes,4,opt,name=mail" json:"mail,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	CfUsername  string `protobuf:"bytes,6,opt,name=cf_username,json=cfUsername" json:"cf_username,omitempty"`
	UvaUsername string `protobuf:"bytes,7,opt,name=uva_username,json=uvaUsername" json:"uva_username,omitempty"`
	Status      string `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
}

func (m *SignupRequest) Reset()                    { *m = SignupRequest{} }
func (m *SignupRequest) String() string            { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()               {}
func (*SignupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SigninRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *SigninRequest) Reset()                    { *m = SigninRequest{} }
func (m *SigninRequest) String() string            { return proto.CompactTextString(m) }
func (*SigninRequest) ProtoMessage()               {}
func (*SigninRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SignupRequest)(nil), "auth.SignupRequest")
	proto.RegisterType((*SigninRequest)(nil), "auth.SigninRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Authentication service

type AuthenticationClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Signout(ctx context.Context, in *dtypes.VoidResponse, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
}

type authenticationClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationClient(cc *grpc.ClientConn) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/auth.Authentication/Signup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/auth.Authentication/Signin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) Signout(ctx context.Context, in *dtypes.VoidResponse, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/auth.Authentication/Signout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Authentication service

type AuthenticationServer interface {
	Signup(context.Context, *SignupRequest) (*dtypes.VoidResponse, error)
	Signin(context.Context, *SigninRequest) (*dtypes.VoidResponse, error)
	Signout(context.Context, *dtypes.VoidResponse) (*dtypes.VoidResponse, error)
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigninRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Signin(ctx, req.(*SigninRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_Signout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dtypes.VoidResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Signout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/Signout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Signout(ctx, req.(*dtypes.VoidResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Authentication_Signup_Handler,
		},
		{
			MethodName: "Signin",
			Handler:    _Authentication_Signin_Handler,
		},
		{
			MethodName: "Signout",
			Handler:    _Authentication_Signout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x95, 0x50, 0xd2, 0xe2, 0x02, 0x83, 0x41, 0x25, 0x4a, 0x2b, 0x41, 0x3d, 0x21, 0x24,
	0x1a, 0x09, 0x36, 0x36, 0x26, 0xf6, 0x22, 0x2a, 0x31, 0x21, 0x37, 0x75, 0x83, 0xa5, 0xd4, 0x36,
	0xb1, 0x4d, 0xc5, 0xca, 0x2b, 0x30, 0xf2, 0x58, 0x3c, 0x00, 0x0b, 0x0f, 0x82, 0x2f, 0x4d, 0x48,
	0x51, 0x59, 0x98, 0x72, 0x2e, 0xbf, 0x3f, 0xfb, 0x3f, 0x27, 0x00, 0x60, 0xad, 0x1e, 0x47, 0xa2,
	0xe4, 0x8a, 0xc3, 0x96, 0x8d, 0x93, 0x41, 0xce, 0x79, 0x5e, 0x90, 0x14, 0x0b, 0x9a, 0x62, 0xc6,
	0xb8, 0xc2, 0x8a, 0x72, 0x26, 0xbd, 0x26, 0xe9, 0x2f, 0xc9, 0xf4, 0xdc, 0xb6, 0x66, 0xea, 0x45,
	0x10, 0xb9, 0xfa, 0xf8, 0x26, 0xfa, 0x0c, 0xc0, 0xde, 0x2d, 0xcd, 0x99, 0x16, 0x63, 0xf2, 0xa4,
	0x89, 0x54, 0x10, 0x82, 0x56, 0xc9, 0x8b, 0x22, 0x0e, 0x4e, 0x82, 0xd3, 0x9d, 0xb1, 0x8b, 0x61,
	0x02, 0x3a, 0x5a, 0x92, 0x92, 0xe1, 0x05, 0x89, 0x43, 0x57, 0xaf, 0x73, 0xab, 0x77, 0xf5, 0x2d,
	0xaf, 0xaf, 0x6a, 0x0b, 0x4c, 0x8b, 0xb8, 0xe5, 0x6b, 0x36, 0xb6, 0x0c, 0x81, 0xa5, 0x5c, 0xf2,
	0x72, 0x16, 0x6f, 0x7b, 0x46, 0x95, 0xc3, 0x63, 0xd0, 0xcd, 0xe6, 0x0f, 0xf5, 0x15, 0x91, 0x6b,
	0x83, 0x6c, 0x7e, 0x57, 0x5d, 0x32, 0x04, 0xbb, 0xfa, 0x19, 0xff, 0x28, 0xda, 0x4e, 0xd1, 0x35,
	0xb5, 0x5a, 0xd2, 0x03, 0x91, 0x34, 0xc6, 0xb5, 0x8c, 0x3b, 0xae, 0xb9, 0xca, 0xd0, 0x8d, 0x37,
	0x48, 0x59, 0x65, 0xb0, 0x69, 0x26, 0xf8, 0x65, 0xa6, 0xf9, 0xc8, 0x70, 0xfd, 0x91, 0x17, 0xef,
	0x21, 0xd8, 0xbf, 0x36, 0xe3, 0x26, 0x4c, 0xd1, 0xcc, 0x4d, 0x18, 0x4e, 0x40, 0xe4, 0x87, 0x07,
	0x0f, 0x46, 0x6e, 0x2b, 0x6b, 0xa3, 0x4c, 0x0e, 0x47, 0xab, 0x59, 0x4f, 0x38, 0x9d, 0x8d, 0x89,
	0x14, 0x66, 0x29, 0x04, 0x0d, 0x5f, 0x3f, 0xbe, 0xde, 0xc2, 0x3e, 0xea, 0xa5, 0x32, 0xa7, 0x22,
	0xf3, 0x5b, 0x33, 0x87, 0x53, 0xe9, 0x0e, 0x5f, 0x05, 0x67, 0x15, 0x97, 0xb2, 0x26, 0xb7, 0x76,
	0xf0, 0x1f, 0x2e, 0x65, 0x96, 0x7b, 0x0f, 0xda, 0x96, 0xc4, 0xb5, 0x82, 0x1b, 0x19, 0x7f, 0x90,
	0x91, 0x23, 0x0f, 0xd0, 0xd1, 0x26, 0xb2, 0x81, 0x19, 0xf4, 0x34, 0x72, 0xff, 0xd3, 0xe5, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x8e, 0x3c, 0x9d, 0x9e, 0x02, 0x00, 0x00,
}
