// Code generated by protoc-gen-go.
// source: dtypes.proto
// DO NOT EDIT!

/*
Package dtypes is a generated protocol buffer package.

It is generated from these files:
	dtypes.proto

It has these top-level messages:
	Status
	Help
	ErrorDetails
	LongRunningResponse
	VoidRequest
	VoidResponse
*/
package dtypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Next Id = 20
type StatusCode int32

const (
	// Not an error. Returned on success.
	// Similar to HTTP Status code 2**.
	StatusCode_OK StatusCode = 0
	// Request Unsucesful
	StatusCode_FAILED StatusCode = 1
	// The request does not have valid authentication credentials for the
	// operation. Similar to HTTP status code 401.
	StatusCode_UNAUTHORIZED StatusCode = 2
	// The request contains invalid arguments.
	// Similar to HTTP status code 400
	StatusCode_BADREQUEST StatusCode = 3
	// The caller does not have permission to execute the specified
	// operation. Reserved For further use.
	// Similar to HTTP Status code 403
	StatusCode_PERMISSION_DENIED StatusCode = 4
	// Requested entity not found.
	// Similar to HTTP status code 404
	StatusCode_NOT_FOUND StatusCode = 5
	// The operation is not implemented or is not supported/enabled
	// Similar to HTTP status code 501
	StatusCode_UNIMPLEMENTED StatusCode = 6
	// Internal errors. This means that some invariants expected by the
	// underlying system have been broken.
	// Similar to HTTP status code 500
	StatusCode_INTERNAL StatusCode = 7
	// External Server Refuses Connection or Sends Invalid Data.
	StatusCode_EXTERNAL StatusCode = 8
	// The response contains invalid arguments.
	StatusCode_BAD_RESPONSE StatusCode = 9
	// Unknown error.
	// Errors raised by APIs that do not return enough error information
	// may be converted to this error.
	// Similar to HTTP status code 500
	StatusCode_UNKNOWN_ERROR StatusCode = 10
	// Quota and payment related error codes.
	// client request crossses the exisitng quta limits.
	StatusCode_QUOTA_LIMIT_EXCEED StatusCode = 11
	// no valid quta available
	StatusCode_INVALID_QUOTA StatusCode = 12
	// no payment informtaion avaible
	StatusCode_PAYMENT_INFORMATION_UNAVAILABLE StatusCode = 13
	// payment information not valid.
	StatusCode_INVALID_PAYMENT_INFORMATION StatusCode = 14
	// failed to transect the payment information
	StatusCode_TRANSACTION_FAILED StatusCode = 15
	// to give ARE_YOU_SURE option
	StatusCode_ARE_YOU_SURE StatusCode = 16
	// invalied data
	StatusCode_INVALIED_DATA StatusCode = 17
)

var StatusCode_name = map[int32]string{
	0:  "OK",
	1:  "FAILED",
	2:  "UNAUTHORIZED",
	3:  "BADREQUEST",
	4:  "PERMISSION_DENIED",
	5:  "NOT_FOUND",
	6:  "UNIMPLEMENTED",
	7:  "INTERNAL",
	8:  "EXTERNAL",
	9:  "BAD_RESPONSE",
	10: "UNKNOWN_ERROR",
	11: "QUOTA_LIMIT_EXCEED",
	12: "INVALID_QUOTA",
	13: "PAYMENT_INFORMATION_UNAVAILABLE",
	14: "INVALID_PAYMENT_INFORMATION",
	15: "TRANSACTION_FAILED",
	16: "ARE_YOU_SURE",
	17: "INVALIED_DATA",
}
var StatusCode_value = map[string]int32{
	"OK":                              0,
	"FAILED":                          1,
	"UNAUTHORIZED":                    2,
	"BADREQUEST":                      3,
	"PERMISSION_DENIED":               4,
	"NOT_FOUND":                       5,
	"UNIMPLEMENTED":                   6,
	"INTERNAL":                        7,
	"EXTERNAL":                        8,
	"BAD_RESPONSE":                    9,
	"UNKNOWN_ERROR":                   10,
	"QUOTA_LIMIT_EXCEED":              11,
	"INVALID_QUOTA":                   12,
	"PAYMENT_INFORMATION_UNAVAILABLE": 13,
	"INVALID_PAYMENT_INFORMATION":     14,
	"TRANSACTION_FAILED":              15,
	"ARE_YOU_SURE":                    16,
	"INVALIED_DATA":                   17,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status struct {
	// Response status code
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// Response status code string.
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	// User facing message.
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	// Optional. Help link if there is an error.
	Help *Help `protobuf:"bytes,4,opt,name=help" json:"help,omitempty"`
	// A list of messages that carry the error details.  There will be a
	// common set of message types for APIs to use.
	Details []*google_protobuf.Any `protobuf:"bytes,5,rep,name=details" json:"details,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Status) GetHelp() *Help {
	if m != nil {
		return m.Help
	}
	return nil
}

func (m *Status) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

// Provides links to documentation or for performing an out of band action.
// Next Id = 3
type Help struct {
	// Describe what link offers
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// The URL of The link.
	Url string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *Help) Reset()                    { *m = Help{} }
func (m *Help) String() string            { return proto.CompactTextString(m) }
func (*Help) ProtoMessage()               {}
func (*Help) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Basic Error details message to send in response. Application specific
// error messages can be provided.
type ErrorDetails struct {
	RequestedResource string `protobuf:"bytes,1,opt,name=requested_resource,json=requestedResource" json:"requested_resource,omitempty"`
	Stacktrace        string `protobuf:"bytes,2,opt,name=stacktrace" json:"stacktrace,omitempty"`
}

func (m *ErrorDetails) Reset()                    { *m = ErrorDetails{} }
func (m *ErrorDetails) String() string            { return proto.CompactTextString(m) }
func (*ErrorDetails) ProtoMessage()               {}
func (*ErrorDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Types for long running operation. usually called as jobs.
// Next Id = 3
type LongRunningResponse struct {
	Status  *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	JobPhid string  `protobuf:"bytes,2,opt,name=job_phid,json=jobPhid" json:"job_phid,omitempty"`
}

func (m *LongRunningResponse) Reset()                    { *m = LongRunningResponse{} }
func (m *LongRunningResponse) String() string            { return proto.CompactTextString(m) }
func (*LongRunningResponse) ProtoMessage()               {}
func (*LongRunningResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LongRunningResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type VoidRequest struct {
}

func (m *VoidRequest) Reset()                    { *m = VoidRequest{} }
func (m *VoidRequest) String() string            { return proto.CompactTextString(m) }
func (*VoidRequest) ProtoMessage()               {}
func (*VoidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type VoidResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *VoidResponse) Reset()                    { *m = VoidResponse{} }
func (m *VoidResponse) String() string            { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()               {}
func (*VoidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VoidResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "dtypes.Status")
	proto.RegisterType((*Help)(nil), "dtypes.Help")
	proto.RegisterType((*ErrorDetails)(nil), "dtypes.ErrorDetails")
	proto.RegisterType((*LongRunningResponse)(nil), "dtypes.LongRunningResponse")
	proto.RegisterType((*VoidRequest)(nil), "dtypes.VoidRequest")
	proto.RegisterType((*VoidResponse)(nil), "dtypes.VoidResponse")
	proto.RegisterEnum("dtypes.StatusCode", StatusCode_name, StatusCode_value)
}

func init() { proto.RegisterFile("dtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xa5, 0x1f, 0x4b, 0xb7, 0xdb, 0x74, 0xb8, 0xe6, 0x43, 0x1d, 0x48, 0x6c, 0x2a, 0x12, 0x42,
	0x48, 0x74, 0x12, 0x48, 0x3c, 0xf0, 0xe6, 0x2d, 0x9e, 0x66, 0x2d, 0x75, 0x3a, 0x27, 0x19, 0x1b,
	0x12, 0xb2, 0xba, 0xd6, 0x74, 0x85, 0x12, 0x87, 0x7c, 0x3c, 0xec, 0xdf, 0xf0, 0xfb, 0xf8, 0x15,
	0x38, 0x5f, 0x63, 0x0f, 0xbc, 0xf0, 0x14, 0x9f, 0x73, 0x8f, 0xef, 0x3d, 0xf7, 0xc4, 0x60, 0x2f,
	0xb3, 0xdb, 0x58, 0xa5, 0x93, 0x38, 0xd1, 0x99, 0xc6, 0x56, 0x85, 0x9e, 0xed, 0xad, 0xb4, 0x5e,
	0x6d, 0xd4, 0x61, 0xc9, 0x5e, 0xe7, 0x5f, 0x0f, 0xe7, 0xd1, 0x6d, 0x25, 0x19, 0xff, 0x6a, 0x81,
	0xe5, 0x67, 0xf3, 0x2c, 0x4f, 0x31, 0x86, 0xee, 0x42, 0x2f, 0xd5, 0xa8, 0x75, 0xd0, 0x7a, 0xbd,
	0x23, 0xca, 0x33, 0x7e, 0x0a, 0x56, 0x5a, 0x56, 0x47, 0xed, 0x92, 0xad, 0x11, 0x1e, 0x41, 0xef,
	0x87, 0x4a, 0xd3, 0xf9, 0x4a, 0x8d, 0x3a, 0x65, 0xa1, 0x81, 0xf8, 0x00, 0xba, 0x37, 0x6a, 0x13,
	0x8f, 0xba, 0x86, 0xee, 0xbf, 0xb3, 0x27, 0xb5, 0xa1, 0x53, 0xc3, 0x89, 0xb2, 0x82, 0x27, 0xd0,
	0x5b, 0xaa, 0x6c, 0xbe, 0xde, 0xa4, 0xa3, 0xad, 0x83, 0x8e, 0x11, 0x3d, 0x9e, 0x54, 0xfe, 0x26,
	0x8d, 0xbf, 0x09, 0x89, 0x6e, 0x45, 0x23, 0x1a, 0x7f, 0x84, 0x6e, 0x71, 0xdb, 0x74, 0xee, 0x2f,
	0x55, 0xba, 0x48, 0xd6, 0x71, 0xb6, 0xd6, 0x51, 0x6d, 0xf3, 0x3e, 0x85, 0x11, 0x74, 0xf2, 0x64,
	0x53, 0x5b, 0x2d, 0x8e, 0xe3, 0x2f, 0x60, 0xd3, 0x24, 0xd1, 0x89, 0x53, 0xf5, 0xc2, 0x6f, 0x01,
	0x27, 0xea, 0x67, 0xae, 0xd2, 0x4c, 0x2d, 0x65, 0xa2, 0x52, 0x9d, 0x27, 0x8b, 0x66, 0xe3, 0xe1,
	0x5d, 0x45, 0xd4, 0x05, 0xfc, 0x02, 0xc0, 0x2c, 0xbc, 0xf8, 0x9e, 0x25, 0x73, 0x23, 0xab, 0xfa,
	0xde, 0x63, 0xc6, 0x97, 0xf0, 0xc8, 0xd5, 0xd1, 0x4a, 0xe4, 0x51, 0xb4, 0x36, 0x1f, 0x95, 0xc6,
	0x3a, 0x4a, 0x15, 0x7e, 0x75, 0x97, 0x5a, 0xab, 0x4c, 0x61, 0xb7, 0x49, 0xa1, 0x4a, 0xfa, 0x2e,
	0xc5, 0x3d, 0xd8, 0xfe, 0xa6, 0xaf, 0x65, 0x7c, 0xb3, 0x5e, 0xd6, 0xcd, 0x7b, 0x06, 0xcf, 0x0c,
	0x1c, 0x0f, 0xa0, 0x7f, 0xa1, 0xd7, 0xc6, 0x49, 0x69, 0x69, 0xfc, 0x01, 0xec, 0x0a, 0xfe, 0xdf,
	0x84, 0x37, 0xbf, 0xdb, 0x00, 0x15, 0x75, 0x5c, 0xfc, 0x4e, 0x0b, 0xda, 0xde, 0x19, 0x7a, 0x80,
	0x01, 0xac, 0x13, 0xc2, 0x5c, 0xea, 0xa0, 0x96, 0x09, 0xcd, 0x0e, 0x39, 0x09, 0x83, 0x53, 0x4f,
	0xb0, 0xcf, 0x86, 0x69, 0xe3, 0x5d, 0x80, 0x23, 0xe2, 0x08, 0x7a, 0x1e, 0x52, 0x3f, 0x40, 0x1d,
	0xfc, 0x04, 0x86, 0x33, 0x2a, 0xa6, 0xcc, 0xf7, 0x99, 0xc7, 0xa5, 0x43, 0x39, 0x33, 0xb2, 0x2e,
	0x1e, 0xc0, 0x0e, 0xf7, 0x02, 0x79, 0xe2, 0x85, 0xdc, 0x41, 0x5b, 0x78, 0x08, 0x83, 0x90, 0xb3,
	0xe9, 0xcc, 0xa5, 0x53, 0xca, 0x03, 0xa3, 0xb0, 0xb0, 0x0d, 0xdb, 0xcc, 0x1c, 0x05, 0x27, 0x2e,
	0xea, 0x15, 0x88, 0x5e, 0xd6, 0x68, 0xbb, 0x18, 0x6b, 0x86, 0x48, 0x41, 0xfd, 0x99, 0xc7, 0x7d,
	0x8a, 0x76, 0xaa, 0x06, 0x67, 0xdc, 0xfb, 0xc4, 0x25, 0x15, 0xc2, 0x13, 0x08, 0xcc, 0xf3, 0xc3,
	0xe7, 0xa1, 0x17, 0x10, 0xe9, 0xb2, 0x29, 0x0b, 0x24, 0xbd, 0x3c, 0xa6, 0xa6, 0x71, 0xbf, 0x90,
	0x32, 0x7e, 0x41, 0x5c, 0xe6, 0xc8, 0xb2, 0x8e, 0x6c, 0xfc, 0x12, 0xf6, 0x67, 0xe4, 0xaa, 0x18,
	0x2d, 0x19, 0x3f, 0xf1, 0xc4, 0x94, 0x04, 0x85, 0x5b, 0xb3, 0xda, 0x85, 0xd9, 0x94, 0x1c, 0xb9,
	0x14, 0x0d, 0xf0, 0x3e, 0x3c, 0x6f, 0xee, 0xfd, 0x43, 0x8c, 0x76, 0x8b, 0x81, 0x81, 0x20, 0xdc,
	0x27, 0xc7, 0xe5, 0xed, 0x3a, 0xa4, 0x87, 0x85, 0x5b, 0x22, 0xa8, 0xbc, 0xf2, 0x42, 0xe9, 0x87,
	0x82, 0x22, 0xf4, 0xd7, 0x02, 0x75, 0xa4, 0x43, 0x8c, 0x85, 0xe1, 0xb5, 0x55, 0xbe, 0xdf, 0xf7,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xad, 0x7e, 0x95, 0x85, 0x03, 0x00, 0x00,
}
