// Code generated by protoc-gen-go.
// source: dtypes.proto
// DO NOT EDIT!

/*
Package dtypes is a generated protocol buffer package.

It is generated from these files:
	dtypes.proto

It has these top-level messages:
	Status
	VoidRequest
	VoidResponse
*/
package dtypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	// Similar to HTTP Status code 2**.
	StatusCode_OK     StatusCode = 0
	StatusCode_FAILED StatusCode = 1
	// operation. Similar to HTTP status code 401.
	StatusCode_UNAUTHORIZED StatusCode = 2
	// Similar to HTTP status code 400
	StatusCode_BADREQUEST StatusCode = 3
	// Similar to HTTP Status code 403
	StatusCode_PERMISSION_DENIED StatusCode = 4
	// Similar to HTTP status code 404
	StatusCode_NOT_FOUND StatusCode = 5
	// Similar to HTTP status code 500
	StatusCode_UNKNOWN_ERROR StatusCode = 6
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "FAILED",
	2: "UNAUTHORIZED",
	3: "BADREQUEST",
	4: "PERMISSION_DENIED",
	5: "NOT_FOUND",
	6: "UNKNOWN_ERROR",
}
var StatusCode_value = map[string]int32{
	"OK":                0,
	"FAILED":            1,
	"UNAUTHORIZED":      2,
	"BADREQUEST":        3,
	"PERMISSION_DENIED": 4,
	"NOT_FOUND":         5,
	"UNKNOWN_ERROR":     6,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status struct {
	// Response status code
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// Response status code string.
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	// User facing message.
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VoidRequest struct {
}

func (m *VoidRequest) Reset()                    { *m = VoidRequest{} }
func (m *VoidRequest) String() string            { return proto.CompactTextString(m) }
func (*VoidRequest) ProtoMessage()               {}
func (*VoidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VoidResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *VoidResponse) Reset()                    { *m = VoidResponse{} }
func (m *VoidResponse) String() string            { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()               {}
func (*VoidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VoidResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "dtypes.Status")
	proto.RegisterType((*VoidRequest)(nil), "dtypes.VoidRequest")
	proto.RegisterType((*VoidResponse)(nil), "dtypes.VoidResponse")
	proto.RegisterEnum("dtypes.StatusCode", StatusCode_name, StatusCode_value)
}

func init() { proto.RegisterFile("dtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xdd, 0x0f, 0x23, 0x7b, 0x6b, 0x47, 0xf6, 0x40, 0x29, 0xe2, 0x41, 0x7a, 0x10, 0xf1,
	0xb0, 0x81, 0x82, 0xf7, 0x6a, 0x33, 0x2c, 0xd3, 0x44, 0xd3, 0x56, 0xc1, 0x4b, 0xa9, 0x36, 0x94,
	0x82, 0x36, 0xd5, 0x74, 0x07, 0xf1, 0x9f, 0xb7, 0x6b, 0x3b, 0x6f, 0xf9, 0x7c, 0xde, 0x23, 0xdf,
	0x2f, 0x0f, 0xac, 0xac, 0xfe, 0xa9, 0x94, 0x59, 0x54, 0xdf, 0xba, 0xd6, 0x48, 0x3a, 0x3a, 0x3e,
	0xc9, 0xb5, 0xce, 0x3f, 0xd4, 0x32, 0xad, 0x8a, 0x65, 0x5a, 0x96, 0xba, 0x4e, 0xeb, 0x42, 0x97,
	0xfd, 0x96, 0xcb, 0x81, 0x84, 0x8d, 0xd9, 0x18, 0x44, 0x18, 0xbf, 0xeb, 0x4c, 0x39, 0x83, 0xd3,
	0xc1, 0xf9, 0x44, 0xb6, 0x6f, 0x3c, 0x02, 0x62, 0xda, 0xa9, 0x33, 0x6c, 0x6d, 0x4f, 0xe8, 0xc0,
	0xc1, 0xa7, 0x32, 0x26, 0xcd, 0x95, 0x33, 0x6a, 0x07, 0x3b, 0x74, 0x6d, 0x98, 0x3e, 0xeb, 0x22,
	0x93, 0xea, 0x6b, 0xa3, 0x4c, 0xed, 0x5e, 0x83, 0xd5, 0xa1, 0xa9, 0x9a, 0x4c, 0x85, 0x67, 0xff,
	0x1f, 0x6e, 0x63, 0xa6, 0x97, 0xb3, 0x45, 0xdf, 0xb9, 0x2b, 0xb1, 0x0b, 0xb8, 0xf8, 0x05, 0xe8,
	0xcc, 0xed, 0xb6, 0x06, 0x81, 0xa1, 0x58, 0xd3, 0x3d, 0x04, 0x20, 0x2b, 0x2f, 0xb8, 0x67, 0x3e,
	0x1d, 0x20, 0x05, 0x2b, 0xe6, 0x5e, 0x1c, 0xdd, 0x09, 0x19, 0xbc, 0x36, 0x66, 0x88, 0x33, 0x80,
	0x1b, 0xcf, 0x97, 0xec, 0x29, 0x66, 0x61, 0x44, 0x47, 0x78, 0x08, 0xf3, 0x47, 0x26, 0x1f, 0x82,
	0x30, 0x0c, 0x04, 0x4f, 0x7c, 0xc6, 0x83, 0x66, 0x6d, 0x8c, 0x36, 0x4c, 0xb8, 0x88, 0x92, 0x95,
	0x88, 0xb9, 0x4f, 0xf7, 0x71, 0x0e, 0x76, 0xcc, 0xd7, 0x5c, 0xbc, 0xf0, 0x84, 0x49, 0x29, 0x24,
	0x25, 0x6f, 0xa4, 0x3d, 0xcd, 0xd5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x81, 0x61, 0x52,
	0x50, 0x01, 0x00, 0x00,
}
