// Code generated by protoc-gen-go.
// source: dtypes.proto
// DO NOT EDIT!

/*
Package dtypes is a generated protocol buffer package.

It is generated from these files:
	dtypes.proto

It has these top-level messages:
	Status
	VoidRequest
	VoidResponse
*/
package dtypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	// Response status code
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// Response status code string.
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	// User facing message.
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VoidRequest struct {
}

func (m *VoidRequest) Reset()                    { *m = VoidRequest{} }
func (m *VoidRequest) String() string            { return proto.CompactTextString(m) }
func (*VoidRequest) ProtoMessage()               {}
func (*VoidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VoidResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *VoidResponse) Reset()                    { *m = VoidResponse{} }
func (m *VoidResponse) String() string            { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()               {}
func (*VoidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VoidResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "dtypes.Status")
	proto.RegisterType((*VoidRequest)(nil), "dtypes.VoidRequest")
	proto.RegisterType((*VoidResponse)(nil), "dtypes.VoidResponse")
}

func init() { proto.RegisterFile("dtypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x29, 0xa9, 0x2c,
	0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0x64, 0xd2, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b,
	0x32, 0xf3, 0xf3, 0xa0, 0xaa, 0x94, 0xfc, 0xb8, 0xd8, 0x82, 0x81, 0x22, 0xa5, 0xc5, 0x42, 0x42,
	0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90,
	0x18, 0x17, 0x5b, 0x31, 0x58, 0x56, 0x82, 0x09, 0x2c, 0x0a, 0xe5, 0x09, 0x49, 0x70, 0xb1, 0xe7,
	0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x83, 0x25, 0x60, 0x5c, 0x25, 0x5e, 0x2e, 0xee,
	0xb0, 0xfc, 0xcc, 0x94, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x33, 0x2e, 0x1e, 0x08,
	0xb7, 0xb8, 0x00, 0x68, 0x67, 0xaa, 0x90, 0x1a, 0xdc, 0x40, 0x90, 0x35, 0xdc, 0x46, 0x7c, 0x7a,
	0x50, 0x37, 0x43, 0x1c, 0x01, 0xb3, 0x20, 0x89, 0x0d, 0xec, 0x3a, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x93, 0xa8, 0x2e, 0xba, 0xd3, 0x00, 0x00, 0x00,
}
